language: go

sudo: false

go: 
    - master

before_install:
    - go get -t -v ./...

script:
    - GOOS=darwin go build
    - GOOS=windows go build
    - GOOS=linux go build
    - go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
    - bash <(curl -s https://codecov.io/bash)
    
